name: Build and Deploy to Railway  

on:  
  push:  
    branches:  
      - main  

env:
  # Setting an environment variable with the value of a configuration variable
  env_RAILWAY_TOKEN: ${{ env.RAILWAY_TOKEN }}

jobs:  
  build-and-deploy:  
    runs-on: ubuntu-latest  
    steps:  
      - uses: actions/checkout@v3  

      - name: Set up Python  
        uses: actions/setup-python@v4  
        with:  
          python-version: '3.12'

      - name: Install dependencies  
        run: |  
          python -m pip install --upgrade pip  
          pip install -r requirements.txt  

      - name: Install Railway CLI  
        run: |  
          curl -sL https://railway.app/install.sh | sh  

      - name: Check key
        run: |
          echo RAILWAY_TOKEN: $env.RAILWAY_TOKEN

      - name: Deploy to Railway  
        run: RAILWAY_TOKEN=$env.RAILWAY_TOKEN railway up